---
title: "STATS 101A Section 1B Kaggle Project"
author: "Karina Santoso, UID- 805291900"
date: "3/22/2021"
output: pdf_document
---

```{r}
library(ggplot2)
library(GGally)
library(corrplot)
library(car)
library(leaps)
cars <- read.csv("carsTrain.csv")
```

```{r}
head(cars)
ggpairs(cars, columns = c(4, 5, 6, 7, 25))
ggpairs(cars, columns = c(8, 9, 10, 11, 25))
ggpairs(cars, columns = c(12, 13, 14, 15, 25))
ggpairs(cars, columns = c(16, 17, 18, 19, 25))
ggpairs(cars, columns = c(20, 21, 22, 23, 25))
```

```{r}
cars$Cylinders2 <- ifelse(cars$Cylinders == 8 | cars$Cylinders == "rotary", 1, 2)
table(factor(cars$Cylinders2))
cars$Engine3 <- ifelse(cars$EngineSize == 1.5, 1, ifelse(cars$EngineSize == 2.1, 2, 
    ifelse(cars$EngineSize == 2.8, 3, ifelse(cars$EngineSize == 3.2, 4, ifelse(cars$EngineSize == 4.9, 5,
    ifelse(cars$EngineSize == 5, 6, 7))))))
cars$Man <- ifelse(cars$Manufacturer == "Mercedes-Benz", 1, ifelse(cars$Manufacturer == "Mercury",2, 
    ifelse(cars$Manufacturer == "Lexus", 3, ifelse(cars$Model == "Crown_Victoria", 4,
    ifelse(cars$Model == "Imperial", 5, ifelse(cars$Model == "Continental", 6, 
    ifelse(cars$Manufacturer == "Audi", 7, ifelse(cars$Manufacturer == "Volvo", 8, 9))))))))
```

```{r}
library(caTools)
set.seed(123456)
Cars.split = sample.split(as.numeric(rownames(cars)), SplitRatio= 0.7)
train.Cars= subset(cars, Cars.split==TRUE)
test.Cars= subset(cars, Cars.split==FALSE)



m0 <- lm((PriceNew)^(1/3)~Type+Weight+factor(Engine3):Horsepower+factor(Man)+ factor(Cylinders2), data = train.Cars)

summary(m0)
anova(m0)
vif(m0)
par(mfrow=c(2,2))
plot(m0)

AIC(m0)
extractAIC(m0,k=log(length(cars$Ob)))

predictions <- predict(m0, newdata = test.Cars)
predictions <- predictions^3

residuals <- (predictions - test.Cars$PriceNew)
plot(residuals, test.Cars$PriceNew)

bigerror <- which(abs(residuals) > 6000)
```

```{r}
test.Cars[bigerror,]
predictions[bigerror]
```

```{r}
leveragePlots(m0)
#mmps(m0)
powerTransform(cbind(cars$Horsepower, cars$Fuel.tank.capacity, cars$Width, cars$Weight))
inverseResponsePlot(m0)
```

```{r}

ggplot(cars, aes(x=MPG.highway, y=PriceNew, group=Cylinders2, color=Cylinders2))+geom_point(alpha = 0.3, position = position_jitter()) + stat_smooth(method = "lm")
```

```{r}

test <- read.csv("carsTestNoY.csv")
test$Engine <- ifelse(test$EngineSize < 2.8 | test$EngineSize == 3 | test$EngineSize == 3.5, 1, 
                      ifelse(test$EngineSize == 3.2 | test$EngineSize == 4.5, 2, test$EngineSize))
test$Cylinders2 <- ifelse(test$Cylinders == 8 | test$Cylinders == "rotary", 1, 2)

test$Man <- ifelse(test$Manufacturer == "Mercedes-Benz", 1, ifelse(test$Manufacturer == "Mercury",2, ifelse(test$Manufacturer == "Lexus", 3, ifelse(test$Model == "Crown_Victoria", 4, ifelse(test$Model == "Imperial", 5, ifelse(test$Model == "Continental", 6, ifelse(test$Manufacturer == "Audi", 7, ifelse(test$Manufacturer == "Volvo", 8, 9))))))))
test$Engine3 <- ifelse(test$EngineSize == 1.5, 1, ifelse(test$EngineSize == 2.1, 2, ifelse(test$EngineSize == 2.8, 3, ifelse(test$EngineSize == 3.2, 4, ifelse(test$EngineSize == 4.9, 5, ifelse(test$EngineSize == 5, 6, 7))))))
predictions <- predict(m0, newdata = test)
predictions <- predictions^3
submission <- data.frame(Ob = 1:500, PriceNew = predictions)
write.csv(submission, file = "~/Desktop/predictions.csv", row.names = F)
```

